# Generated by Django 3.1 on 2020-09-03 06:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='background_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info',
            field=models.CharField(default='A Health House scientific learning experience created by Norvell Jefferson', max_length=128),
        ),
        migrations.AddField(
            model_name='homepage',
            name='subtitle',
            field=models.CharField(default='Preparing for the next pandemic and beyond', max_length=128),
        ),
    ]
